name: 'Github Release Tags'
description:
  Parse git version tag, branch and generate publishable tags that identify the
  current build.
inputs:
  tags-prefix:
    description:
      Prefix to add to all tags separated by a dash. When a prefix is present,
      the "latest" tag will actually be just the provided prefix.
    required: false
    default: ''
  force-latest:
    description:
      Always generate the "latest" tag in any context.
    required: false
    default: "false"
  always-latest-on-branch:
    description:
      Always generate the "latest" tag when executing on the specified branch.
    required: false
    default: ''
outputs:
  version:
    description: "Tag pointing to the current commit as obtained from `git describe`"
    value: ${{ steps.release-tags.outputs.version }}
  branches:
    description: "Branches pointing to the current commit as obtained from `git branch`"
    value: ${{ steps.release-tags.outputs.branches }}
  tags:
    description:
      Tags that should be published for the current build. Includes `version`,
      `branches` and potentially "latest" if version is a stable semver.
    value: ${{ steps.release-tags.outputs.tags }}
runs:
  using: "composite"
  steps:
    - id: release-tags
      shell: bash
      run: ${{ github.action_path }}/release-tags.sh
      env:
        TAGS_PREFIX: ${{ inputs.tags-prefix }}
        FORCE_LATEST: ${{ inputs.force-latest }}
        ALWAYS_LATEST_ON_BRANCH: ${{ inputs.always-latest-on-branch }}
